### ISSUE TITLE
Regarding the number of clips and train/test split

### ISSUE THREAD

**Issue by avijit9** [Chiaraplizz/ARGO1M-What-can-a-cook#2]
Hi @Chiaraplizz ,

Great work! 

I've noticed that the 30 CSV files I found contain a total of 8,674,566 clips, whereas the paper mentions that the dataset should have 1 million videos. I feel like I might be missing something here and was hoping you could assist me. I understand that you applied scenario-based filtering, as outlined in the paper. Can you please help me here?

**Comment by Chiaraplizz** [comment]
Hello!

That's because the training sets of the different splits have overlapping clips. In fact, each split has been obtained through leave-one-out of a certain (scenario, location) combination. You should not consider the duplicates across the different training sets when considering the total number of samples.

Let me know if everything is clear now!

**Comment by avijit9** [comment]
Hi, thanks for your prompt reply. 

I checked the `Arts_and_craft_ITA_train.csv`. I think it has greater than 700k samples alone. That is where I am getting confused. 

How do I exactly obtain the train, val, and test split for fair comparisons?

**Comment by avijit9** [comment]
Okay. I got it. If I read all csvs and store them in a single data frame `df`, then `len(concatenated_df.drop_duplicates())` gives the unique clips which I am getting `1050371` close to what mentioned in the paper `1050396`.

Thanks!
